### ISSUE TITLE
Cyclic digraph

### ISSUE THREAD

**Issue by Nullpo** [HQarroum/directed-graph#2]
Hi!

Do you recommend a way to manage cyclic digraphs? Currently I've got a 'Maximum call stack trace' exception when I find routes in a cyclic digraph.

Thank you!

**Comment by HQarroum** [comment]
Hi!

Thanks for using this library! :smile:

I was indeed aware of this problem (shame on me) which ocurred while using the internal `Stacked` iterator used by the `.routes` API.

One potential solution I've implemented is to determine if the current node has been previously visited. If it is, we simply ignore it. You can checkout the diff [here ](https://github.com/HQarroum/directed-graph/commit/8a8895331917b198ca4789e90b06bb22101d2a25) and tell me what you think.

You'd have to make your test with the current revision on `master` since I won't create a new version, and hence, push it on NPM and Bower until this is correctly fixed.

Any feedback will be appreciated :wink:

**Comment by Nullpo** [comment]
I'm using your tool in production since august, and we didn't have any trouble. I'm waiting to have free time to see how help you with this project :).

Thanks you!!!!

**Comment by HQarroum** [comment]
Awesome! Thanks for the feedback! As always, help is always greatly appreciated, I have some plans for this module in terms of improving its performance and code size.

I'll also take care of making a new release with this fix, again, thanks 😉 !
