### ISSUE TITLE
how can it be used?

### ISSUE THREAD

**Issue by kaanguru** [HQarroum/directed-graph#24]
What can directed-graph library be used for? 
Is there any use case example?
Sorry I couldn't know where to ask thats why I created this new issue.

**Comment by HQarroum** [comment]
Hi @kaanguru, I mainly created this library for using directed graphs in general, my personal use-cases involved finding shortest paths in a graph populated with multiple nodes for network routing. Since it is general purpose, there isn’t a specific example that i’ve associated with it. Could you tell me more about what you want to do ?

**Comment by kaanguru** [comment]
Can I use it as an helper to build database queries_?

https://stackoverflow.com/questions/60174233/can-graphlib-be-used-to-generate-graphql-queries

**Comment by HQarroum** [comment]
I've never done that personally, I think it depends on the use-case involving generating GraphQL queries dynamically. But in theory yeah if you do need to do that you'd have to store nodes and edges and write the code to generate queries. However note that this library keeps your data in memory, there's no persistent storage used. If you need that, I would advise to use a graph database. https://neo4j.com/developer/graphql/
